stphnt/zproto

.github/workflows/ci.yml
.github/workflows/release.yml

This does will never successfully publish a release. I am just checking if the action will trigger appropriately.

Add CI to automatically publish releases to crates.io

---

.github/workflows/release.yml

Remove the `--dry-run` argument so the crate will actually be published.

Allow the release workflow to publish to crates.io

---

src/ascii/port.rs
src/error/ascii.rs

Allow explicit type parameters on the methods of ascii::Port and other types

---

src/ascii.rs
src/ascii/port.rs
src/binary.rs
src/binary/port.rs

Zaber products use ports 55550 and 55551 for TCP connections.

Fix incorrect TCP port examples

---

src/ascii/port.rs

Prior to this change ascii::Port::id() would not return the correct
value. This change corrects that and adds regression tests for the
behaviour.
Fixes #35

Fix bug in ascii::Port::id()

---

examples/binary.rs
src/binary.rs
src/binary/port.rs
test/binary/01-type-inference.rs
test/binary/01-type-inference.stderr
test/binary/02-port-parameters.rs
test/binary/02-port-parameters.stderr
test/binary/03-reply-data.rs

`tx` and `rx` are easily mistyped for one another. Replace `rx` with `recv`, which is also the name used in `std`.
Fixes #43

Rename `rx` to `recv`

---

src/ascii/port.rs

Use RECV instead of RX to make it easier to distinguish from TX.
However, keep the packet bytes aligned between log entries for easier
reading.

Update logging format

---

src/error/binary.rs

Previously users could get the name of binary error codes from the [`BinaryCommandFailureError::name()`](file:///home/stephen/Projects/zproto/target/doc/zproto/error/struct.BinaryCommandFailureError.html#) method. However, if users only have access to the a `binary::Message` it would still be good for them to be able to get the name of the error code. This change allows that.

Expose error::binary_code::name

---

src/binary/command.rs

Make binary::command::name() return proper values

---

src/ascii/port.rs

This reverts commit ae60e4614fe3dfcdd2f22f0381e12edc4f2b73e1.
Unchecked messages are almost never what a customer should be doing. They can already not check a message using the `*_with_check()` methods, so we shouldn't be making it easy for people to do it or pushing them towards it with their APIs.

Revert "Add Port::*_unchecked() methods"

---

src/ascii.rs

Remove unused `use` statements from example code

---

src/ascii/port.rs
src/ascii/response.rs
src/ascii/response/alert.rs
src/ascii/response/builder.rs
src/ascii/response/check.rs
src/ascii/response/info.rs
src/ascii/response/reply.rs
src/error/ascii.rs

Previously the contents of all responses were checked with the `check::default()`, which is quite strict, and not appropriate in most cases. This change still uses `check::default()` by default but allows users to customize it.

Allow for custom default response checks

---

src/ascii.rs
src/ascii/command.rs
src/ascii/port.rs
src/ascii/response/alert.rs
src/ascii/response/info.rs
src/ascii/response/reply.rs

The previous API was a mix of constructors and getters. However, the constructors looked like getters, the getters didn't follow the Rust API guidelines (they started with `get_`). This change makes the constructors read more clearly as constructors and makes the getters follow the API guidelines. It also expands the documentation to avoid confusion.
Closes #86

Refactor the `ascii::Target` API

---

test/binary/01-type-inference.stderr
test/binary/02-port-parameters.stderr

The content now matches the output of the latest stable compiler version, 1.69.

Update expected output for binary compile-time tests

---

src/error.rs
src/error/all.rs
src/error/ascii.rs
src/error/binary.rs

Unlike most other errors, IO errors may be unrecoverable (perhaps the device on the other end disconnected abruptly) so it is helpful to know whether that kind of error has occurred.

Add `is_io()` helper method to errors

---

src/ascii/checksum.rs
src/ascii/command.rs
src/ascii/port.rs
src/error/all.rs
src/error/ascii.rs

Previously command that were too long would be ignored by devices. This change uses the ASCII protocol line continuation feature to split long commands into multiple packets so that the devices can receive it.
Fixes #105

Split long commands using line continuations

---

src/ascii/command.rs
src/ascii/port.rs
src/error/all.rs
src/error/ascii.rs

The use of reserved characters can a command's data field may cause a BADCOMMAND rejected but may also cause the command to be ignored or incorrectly interpreted by the device. To avoid these problems check for these characters in the command before writing out the command.
Fixes #108

Disallow reserved characters in command data

---

src/ascii/response/check.rs

Previously the function incorrectly checked that the flag was "OK". This change corrects the bug.
Fixes #122

Fix check::flag_rj()

---

.github/workflows/ci.yml

Type checking should not depend on the host OS, so remove redundant work.

Only run cargo check on ubuntu

---

src/ascii/port.rs
src/binary/port.rs

These methods will make it easier to open a serial port and limit the number of imports callers need to make

Add Port::open_*_options methods

---

src/ascii/chain.rs

Rename methods on ChainOptions and add a Chain::options method to easily create a ChainOptions with less boilerplate.

Refactor Chain related APIs

---

Cargo.toml
README.md

The README previously had 0.3.4 while Cargo.toml had 0.3.5-pre. This was confusing/inconsistent and may have prompted people to think the main source branch was the same as 0.3.4, which it is not. This change makes the versions consistent and avoids any confusion.

Update version to 0.4.0-pre

---

Cargo.toml

Previously all files in the repo were included in the package. Now only relevant files are included.

Only include necessary files when packaging crate

---

src/ascii.rs
src/ascii/port.rs
src/ascii/port/handlers.rs
src/ascii/port/test.rs
src/binary.rs
src/binary/handlers.rs
src/binary/port.rs
src/convert.rs
src/error.rs
src/error/all.rs
src/error/ascii.rs
src/error/binary.rs
src/lib.rs
src/timeout_guard.rs
test/binary/02-port-parameters.stderr

This should fix #156 in a non-breaking way.
It makes the `ascii::Port` and `binary::Port` generic over their callback types. The type parameter's default implements the current behaviour, so existing code will work as before. To allow sending a `Port` between threads, each `Port` now has a `try_into_send` method which will replace the callback type with one requiring `Send`. 
```rust
let sendable_port = Port::open_serial("...")?.try_into_send().unwrap();
// send it to whatever thread you want.
```
This change includes documentation for the new method.

Sendable port

---

src/ascii/port.rs

Previously the code example would render past the width of the generated doc's container.

Format example code

---

src/error/all.rs
src/error/ascii.rs

This error types were accidentally left in `main` after rolling back an API that was never released.

Remove unused and unpublished error types

---

src/backend.rs

I was playing around with the mocks and I thought it would be nice to have a callback function to generate responses based on received commands.
With this pull request, it is possible to do the following:
```rust
backend.set_reply_callback(|x| match std::str::from_utf8(x) {
Ok("/1 io get ai 1\n") => b"@01 0 OK BUSY -- 5.5\r\n".to_vec(),
Ok("/1 lockstep 1 move abs 5\n") => b"@01 0 OK BUSY -- 0\r\n".to_vec(),
Ok("/get pos\n") => b"@01 0 OK BUSY -- 20\r\n@02 0 OK BUSY -- 10.1\r\n".to_vec(),
Ok(i) => panic!("Invalid input {}", i),
Err(e) => panic!("{}", e.to_string()),
});
```
Let me know what you think about this addition.

Add callback function for mocks

---

src/backend.rs

This allows the callback passed to `Mock` to capture mutable state and implement more complicated logic than it could previously.
Relates to #184.

Change `Mock` backend callback signature from a function pointer to a `FnMut`
