stphnt/zproto

- Cargo.toml
> Fix bug preventing Cargo default features from being enabled

- examples/binary.rs
- src/ascii/port.rs
- src/binary/port.rs
> Make checksum and message ID APIs more consistent

- Cargo.toml
> Update serialport dependency to 4.1.0

- src/ascii/port.rs
Previously, the output from the backend was buffered and the contents
of the buffer were filled via `BufReader::fill_buf()`. However, this
function only reads from the reader if its buffer is empty. So, if the
buffer ever contained a partial packet, more data would never be read
and an error would be returned, despite more data likely being available
to be read.
This change removes the buffer and reads from the backend until a
properly framed packet is found.
Fixes #48
> Properly read ASCII packet bytes

- src/ascii/port.rs
- src/binary.rs
- src/binary/port.rs
- src/error/binary.rs
- src/timeout_guard.rs
- test/binary/01-type-inference.rs
- test/binary/01-type-inference.stderr
- test/binary/02-port-parameters.stderr
> Add on_packet hooks

- src/ascii/response/check.rs
> Fix check error message

- src/ascii/port.rs
> Add handler for unexpected ASCII Alert messages

- src/ascii/port.rs
- src/binary/port.rs
> Expand getters and setters

- Cargo.toml
- README.md
> Prepare for version 0.2.0 release

- src/ascii/command.rs
Allow for borrowed and owned data returned by `Command`s.
> Refactor ascii::Command trait

- src/ascii/parse/token.rs
> Make TokenIter::Item = (Token, &str)

- src/ascii/response/check.rs
This adds `check::is_idle`, `check::is_busy`, and `check::flag_rj`.
> Add some ascii checks

- src/ascii/port.rs
> Refactor `Port::poll_until` APIs

- src/ascii/port.rs
- src/binary/port.rs
> Refactor port methods

- src/ascii/port.rs
- src/ascii/response.rs
- src/ascii/response/check.rs
Rename `check::default()` to `check::strict()` and add `check::minimal()`
> Refactor ascii check

- src/ascii/port.rs
- src/ascii/response/check.rs
A near total removal of the changes introduced in #88
> Revert custom ascii check

- Cargo.toml
- README.md
> Bump version to 0.3.2

- .github/workflows/ci.yml
- .github/workflows/release.yml
> Replace actions-rs in CI

- src/ascii/port.rs
- src/error/ascii.rs
> Fix Port::command_reply_infos

- .github/workflows/audit-ci.yml
- .github/workflows/audit-cron.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
Update the version on some actions and reduce the frequency of scheduled audits
> Clean up CI

- src/ascii.rs
- src/ascii/chain.rs
- src/ascii/chain/info.rs
- src/ascii/chain/iter.rs
- src/ascii/chain/setting.rs
- src/ascii/data_type.rs
- src/ascii/marker.rs
- src/ascii/port.rs
- src/ascii/scope.rs
- src/ascii/setting.rs
- src/error/all.rs
- src/error/ascii.rs
- src/lib.rs
- src/shared.rs
> Add basic Chain, Device, and Axis types

- src/ascii/command.rs
- src/ascii/port.rs
- src/ascii/response/check.rs
This should simplify the code and reduce the size of the binaries
> Use &dyn more

- src/ascii/response.rs
This should make the warnings easier to read.
> Customize Debug impl for Warning

- src/ascii/chain/scope.rs
- src/ascii/chain/setting.rs
> Refactor ascii::chain::scope and improve its documentation

- src/ascii/chain.rs
- src/ascii/chain/iter.rs
> Refactor iterators in ascii::chain::iter

- src/ascii/chain/data_type.rs
- src/ascii/chain/setting.rs
> Refactor the ascii::chain::data_type module

- .cspell/project-words.txt
- Cargo.toml
- scripts/generate-apis/src/gen.rs
- src/ascii/setting/mod.inc
> Rename vlatest to v_latest

- test/binary/03-reply-data.rs
- test/binary/03-reply-data.stderr
This makes the tests pass with 1.78
> Add _ prefix to unused variable in binary test

- src/ascii.rs
- src/ascii/chain.rs
- src/ascii/chain/info.rs
- src/ascii/port.rs
- src/ascii/port/handlers.rs
- src/ascii/port/iter.rs
- src/binary.rs
- src/binary/handlers.rs
- src/binary/port.rs
- src/convert.rs
- src/error.rs
- src/error/all.rs
- src/error/ascii.rs
- src/error/binary.rs
- src/lib.rs
- src/timeout_guard.rs
- test/binary/02-port-parameters.stderr
This incorporates the changes for 0.3.5 into `main`.
> Incorporate changes from 0.3.5

- Cargo.toml
- src/ascii/chain.rs
- src/ascii/chain/setting.rs
- src/ascii/port.rs
- src/ascii/port/test.rs
- src/backend.rs
- src/binary/port.rs
> Add a Mock backend and Port::open_mock() methods to use it

- CHANGELOG.md
- Cargo.toml
- README.md
- src/ascii.rs
> Update version 0.4.0

- src/ascii/chain.rs
- src/ascii/chain/iter.rs
- src/ascii/chain/setting.rs
- src/ascii/port.rs
- src/ascii/port/handlers.rs
- src/ascii/port/iter.rs
- src/binary/handlers.rs
- src/binary/port.rs
- src/timeout_guard.rs
Satisfies recent changes to clippy lints.
> Elide lifetimes where possible

- .github/workflows/ci.yml
- src/ascii/port.rs
- src/ascii/port/options.rs
- src/backend.rs
> Unseal Backend trait
